routes/web.php
<?php

use App\Http\Controllers\SegmentsController;
use App\Http\Controllers\SubscribersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'subscribers');
Route::resource('subscribers', SubscribersController::class);
Route::resource('segments', SegmentsController::class);

app/Models/Operator.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Operator extends Model
{
    use HasFactory;

    // Operator Types
    const TEXT = 'text';
    const DATE = 'date';
    public static $operatorTypes = [self::TEXT, self::DATE];

    protected $guarded = ['id'];

    public $timestamps = true;
}

app/Models/Segment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Segment extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function segment_rules()
    {
        return $this->hasMany(SegmentRule::class, 'segment_id');
    }

}

app/Models/SegmentRule.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SegmentRule extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function segment()
    {
        return $this->belongsTo(Segment::class, 'segment_id')->withDefault();
    }
}

app/Models/Subscriber.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Subscriber extends Model
{
    use HasFactory;

    protected $guarded = ['id'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/SegmentsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Operator;
use App\Models\Segment;
use Illuminate\Http\Request;

class SegmentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $page_title = "Segment List";
        $segments   = Segment::latest()->simplePaginate(10);
        return view('segments.index', compact('page_title', 'segments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        $page_title = 'Add New Segment';
        $operators  = Operator::latest()->get();
        return view('segments.create', compact('page_title', 'operators'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        dd($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/SubscribersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SubscribersRequest;
use App\Models\Subscriber;
use Illuminate\Http\Request;

class SubscribersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $page_title  = 'Subscriber List';
        $subscribers = Subscriber::latest()->simplePaginate(10);
        return view('subscribers.index', compact('page_title', 'subscribers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        $page_title = 'Add New Subscriber';
        return view('subscribers.create', compact('page_title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param SubscribersRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(SubscribersRequest $request)
    {
        Subscriber::create($request->except('_token'));
        return redirect()->route('subscribers.index')->with('toast_success', 'Subscriber created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit($id)
    {
        $page_title = "Edit Subscriber";
        $subscriber = Subscriber::findOrFail($id);
        return view('subscribers.edit', compact('page_title', 'subscriber'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param SubscribersRequest $request
     * @param Subscriber $subscriber
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(SubscribersRequest $request, Subscriber $subscriber)
    {
        $subscriber->update($request->except('_token'));
        return redirect()->route('subscribers.index')->with('toast_success', 'Subscriber updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Subscriber $subscriber
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Subscriber $subscriber)
    {
        $subscriber->delete();
        return redirect()->route('subscribers.index')->with('toast_success', 'Subscriber deleted successfully');
    }
}

resources/views/segments/create.blade.php
<x-app :pageTitle="$page_title">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                {{ $page_title }}
            </h3>
        </div>
        <x-form action="{{ route('segments.store') }}" method="POST">
            @include('segments.form-fields')
        </x-form>
    </div>

    <x-slot name="scripts">
        <script>
            let operators = @json($operators);

            function segmentRepeater() {
                let segmentElementCount = $('.segment-element').length;
                let dateOperatorOptions = '';
                let textOperatorOptions = '';
                $('.remove-segment-logic-btn').click(function () {
                    if (confirm('Are you sure?')) {
                        segmentElementCount--;
                        $(this).parent().parent().parent().remove();
                    }
                });
                $('#add-segment-logic').click(function () {
                    let elementData = `
                        <div class="card segment-element" style="border: 1px solid grey; padding: 10px">
                <div class="row">
                    <div class="col-md-12">
                        <button type="button"
                                class="btn btn-danger float-right btn-sm remove-segment-logic-btn">
                            X
                        </button>
                    </div>
                </div>

                <div class="date-field-group">
                    <div class="date-field-element">
                        <div class="form-group row">
                            <div class="col-3">
                                <select name="and[${segmentElementCount}][date_logics][0][type]" id="date-type${segmentElementCount}" class="form-control">
                                    <option value="">Select Date Type</option>
                                    <option value="created_at">Created at</option>
                                    <option value="birth_day">Birth Day</option>
                                </select>
                            </div>
                            <div class="col-3">
                                <select name="and[${segmentElementCount}][date_logics][0][operator]" id="date-logic-operator${segmentElementCount}" class="form-control">
                                    <option value="">Select Logic Operator</option>

                                </select>
                            </div>
              <div class="col-3">
                  <input type="date" id="date${segmentElementCount}" class="form-control" name="and[${segmentElementCount}][date_logics][0][date]">
              </div>
              <div class="col-3">
                  <button type="button" class="btn btn-danger btn-sm remove-date-btn">
                      Delete
                  </button>
                  <button type="button" class="btn btn-primary btn-sm add-date-btn" onclick="dateLogicRepeater(${segmentElementCount})">
                      + Or
                  </button>
              </div>
          </div>
      </div>
  </div>

  <br>

  <div class="text-group">
      <div class="text-element">
          <div class="form-group row">
              <div class="col-3">
                  <select name="and[${segmentElementCount}][text_logics][0][type]" id="text-type${segmentElementCount}" class="form-control">
                      <option value="">Select Text Type</option>
                      <option value="first_name">First name</option>
                      <option value="last_name">Last name</option>
                      <option value="email">Email</option>
                  </select>
              </div>
              <div class="col-3">
                  <select name="and[${segmentElementCount}][text_logics][0][operator]" id="text-logic-operator${segmentElementCount}" class="form-control">
                      <option value="">Select Logic Operator</option>
                  </select>
              </div>
              <div class="col-3">
                  <input type="text" id="text${segmentElementCount}" class="form-control" name="and[${segmentElementCount}][text_logics][0][text]"
                         placeholder="Enter text">
              </div>
              <div class="col-3">
                  <button type="button" class="btn btn-danger btn-sm remove-text-btn">
                      Delete
                  </button>
                  <button type="button" class="btn btn-primary btn-sm add-text-btn" onclick="textLogicRepeater(${segmentElementCount})">
                      + Or
                  </button>
              </div>
          </div>
      </div>
  </div>

</div>
<br>
`;
                    $('.segment-group').append(elementData);
                    $('.remove-segment-logic-btn').click(function () {
                        if (confirm('Are you sure?')) {
                            segmentElementCount--;
                            $(this).parent().parent().parent().remove();
                        }
                    });
                    $('.remove-date-btn').click(function () {
                        if (confirm('Are you sure?')) {
                            dateFieldCount--;
                            $(this).parent().parent().parent().remove();
                        }
                    });
                    $('.remove-text-btn').click(function () {
                        if (confirm('Are you sure?')) {
                            textFieldCount--;
                            $(this).parent().parent().parent().remove();
                        }
                    });
                    segmentElementCount++;
                });
            }

            function dateLogicRepeater(and_index) {
                let dateFieldCount = $('.date-field-element').length;
                let operatorOptions = '';
                operators.forEach(item => {
                    if (item.operator_type === 'date') {
                        operatorOptions += `<option value="${item.logic_operator}">${item.logic_operator}</option>`;
                    }
                });

                let dateFieldElementData = `
                        <div class="date-field-element">
                        <div class="form-group row">
                            <div class="col-3">
                                <select name="and[${and_index}][date_logics][${dateFieldCount}][type]" id="date-type${dateFieldCount}" class="form-control">
                                    <option value="">Select Date Type</option>
                                    <option value="created_at">Created at</option>
                                    <option value="birth_day">Birth Day</option>
                                </select>
                            </div>
                            <div class="col-3">
                                <select name="and[${and_index}][date_logics][${dateFieldCount}][operator]" id="date-logic-operator${dateFieldCount}" class="form-control">
                                    <option value="">Select Logic Operator</option>
                                    ${operatorOptions}

                   </select>
               </div>
               <div class="col-3">
                   <input type="date" id="date${dateFieldCount}" class="form-control" name="and[${and_index}][date_logics][${dateFieldCount}][date]">
               </div>
               <div class="col-3">
                   <button type="button" class="btn btn-danger btn-sm remove-date-btn">
                       Delete
                   </button>
                   <button type="button" class="btn btn-primary btn-sm add-date-btn"
                           onclick="dateLogicRepeater(${and_index})">
                       + Or
                   </button>
               </div>
           </div>
       </div>
`;
                $('.date-field-group').append(dateFieldElementData);
                $('.remove-date-btn').click(function () {
                    if (confirm('Are you sure?')) {
                        dateFieldCount--;
                        $(this).parent().parent().parent().remove();
                    }
                });
                dateFieldCount++;
            }

            function textLogicRepeater(and_index) {
                let textFieldCount = $('.text-element').length;
                let operatorOptions = '';
                operators.forEach(item => {
                    if (item.operator_type === 'text') {
                        operatorOptions += `<option value="${item.logic_operator}">${item.logic_operator}</option>`;
                    }
                });
                let textElementData = `
                        <div class="text-element">
                        <div class="form-group row">
                            <div class="col-3">
                                <select name="and[${and_index}][text_logics][${textFieldCount}][type]" id="text-type${textFieldCount}" class="form-control">
                                    <option value="">Select Text Type</option>
                                    <option value="first_name">First name</option>
                                    <option value="last_name">Last name</option>
                                    <option value="email">Email</option>
                                </select>
                            </div>
                            <div class="col-3">
                                <select name="and[${and_index}][text_logics][${textFieldCount}][operator]" id="text-logic-operator${textFieldCount}" class="form-control">
                                    <option value="">Select Logic Operator</option>
                                    ${operatorOptions}

                    </select>
                </div>
                <div class="col-3">
                    <input type="text" id="text${textFieldCount}" class="form-control" name="and[${and_index}][text_logics][${textFieldCount}][text]"
                           placeholder="Enter text">
                </div>
                <div class="col-3">
                    <button type="button" class="btn btn-danger btn-sm remove-text-btn">
                        Delete
                    </button>
                    <button type="button" class="btn btn-primary btn-sm add-text-btn"
                            onclick="textLogicRepeater(${and_index})">
                        + Or
                    </button>
                </div>
            </div>
        </div>
`;
                $('.text-group').append(textElementData);

                $('.remove-text-btn').click(function () {
                    if (confirm('Are you sure?')) {
                        textFieldCount--;
                        $(this).parent().parent().parent().remove();
                    }
                });
                textFieldCount++;
            }

            $(document).ready(function () {
                segmentRepeater();


                $('.remove-date-btn').click(function () {
                    if (confirm('Are you sure?')) {
                        dateFieldCount--;
                        $(this).parent().parent().parent().remove();
                    }
                });
                $('.remove-text-btn').click(function () {
                    if (confirm('Are you sure?')) {
                        textFieldCount--;
                        $(this).parent().parent().parent().remove();
                    }
                });


            });
        </script>
    </x-slot>
</x-app>

resources/views/segments/edit.blade.php
<x-app :pageTitle="$page_title">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                {{ $page_title }}
            </h3>
        </div>
        <x-form action="{{ route('subscribers.update', $subscriber->id) }}" method="POST">
            @include('subscribers.form-fields')
        </x-form>
    </div>
</x-app>

resources/views/segments/index.blade.php
<x-app :pageTitle="$page_title">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                {{ $page_title }}
                <a href="{{ route('segments.create') }}" class="btn btn-primary float-right">
                    Add New Segment
                </a>
            </h3>
        </div>
        <div class="card-body">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">#SL</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Birth Day</th>
                    <th scope="col">Created At</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                @forelse($segments as $segment)
                    <tr>
                        <th scope="row">{{ $segments->firstItem() + 1 }}</th>
                        <td>{{ $segment->first_name }}</td>
                        <td>{{ $segment->last_name }}</td>
                        <td>{{ $segment->email }}</td>
                        <td>{{ \Carbon\Carbon::parse($segment->birth_day)->format('F j, Y') }}</td>
                        <td>{{ \Carbon\Carbon::parse($segment->create_at)->format('F j, Y - g:ia') }}</td>
                        <td>
                            <a href="{{ route('segments.edit', $segment->id) }}"
                               class="btn btn-info btn-sm">
                                Edit
                            </a>

                            <x-form-button class="btn btn-danger btn-sm"
                                           action="{{ route('segments.destroy', $segment->id) }}" method="DELETE"
                                           formid="delete-form-{{ $segment->id }}" style="display: inline-block"
                                           onclick="makeDeleteRequest(event, {{ $segment->id }})">
                                Delete
                            </x-form-button>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="100%" class="text-center text-danger">
                            No segments found!
                        </td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            <nav aria-label="Page navigation example">
                <ul class="pagination float-right">
                    {{ $segments->links() }}
                </ul>
            </nav>
        </div>
    </div>
</x-app>

resources/views/subscribers/create.blade.php
<x-app :pageTitle="$page_title">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                {{ $page_title }}
            </h3>
        </div>
        <x-form action="{{ route('subscribers.store') }}" method="POST">
            @include('subscribers.form-fields')
        </x-form>
    </div>
</x-app>

resources/views/subscribers/edit.blade.php
<x-app :pageTitle="$page_title">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                {{ $page_title }}
            </h3>
        </div>
        <x-form action="{{ route('subscribers.update', $subscriber->id) }}" method="POST">
            @include('subscribers.form-fields')
        </x-form>
    </div>
</x-app>

resources/views/subscribers/form-fields.blade.php
<div class="card-body">
    <div class="form-group row">
        <div class="col-6">
            <label for="first-name">First Name</label>
            <input type="text" id="first-name" class="form-control" name="first_name"
                   placeholder="Enter first name"
                   value="{{ $subscriber->first_name ?? old('first_name') }}" autofocus>
        </div>
        <div class="col-6">
            <label for="last-name">Last Name</label>
            <input type="text" id="last-name" class="form-control" name="last_name"
                   placeholder="Enter last name"
                   value="{{ $subscriber->last_name ?? old('last_name') }}">
        </div>
    </div>
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" id="email" class="form-control" name="email" placeholder="Enter email"
               value="{{ $subscriber->email ?? old('email') }}">
    </div>
    <div class="form-group">
        <label for="birth-date">Birth Date</label>
        <input type="date" id="birth-date" class="form-control" name="birth_day"
               value="{{ request()->routeIs('subscribers.edit') ? \Carbon\Carbon::parse($subscriber->birth_day)->format('Y-m-d') : '' ?? old('birth_day') }}">
    </div>
</div>

<div class="card-footer pb-5">
    <button type="submit" class="btn btn-primary float-right ml-1">
        {{ request()->routeIs('subscribers.create') ? 'Save' : 'Update' }}
    </button>
    <a href="{{ route('subscribers.index') }}" class="btn btn-dark float-right">Back</a>
</div>

resources/views/subscribers/index.blade.php
<x-app :pageTitle="$page_title">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                {{ $page_title }}
                <a href="{{ route('subscribers.create') }}" class="btn btn-primary float-right">
                    Add New Subscriber
                </a>
            </h3>
        </div>
        <div class="card-body">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">#SL</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Birth Day</th>
                    <th scope="col">Created At</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                @forelse($subscribers as $key => $subscriber)
                    <tr>
                        <th scope="row">{{ $subscribers->firstItem() + $key }}</th>
                        <td>{{ $subscriber->first_name }}</td>
                        <td>{{ $subscriber->last_name }}</td>
                        <td>{{ $subscriber->email }}</td>
                        <td>{{ \Carbon\Carbon::parse($subscriber->birth_day)->format('F j, Y') }}</td>
                        <td>{{ \Carbon\Carbon::parse($subscriber->create_at)->format('F j, Y - g:ia') }}</td>
                        <td>
                            <a href="{{ route('subscribers.edit', $subscriber->id) }}"
                               class="btn btn-info btn-sm">
                                Edit
                            </a>

                            <x-form-button class="btn btn-danger btn-sm"
                                           action="{{ route('subscribers.destroy', $subscriber->id) }}" method="DELETE"
                                           formid="delete-form-{{ $subscriber->id }}" style="display: inline-block"
                                           onclick="makeDeleteRequest(event, {{ $subscriber->id }})">
                                Delete
                            </x-form-button>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="100%" class="text-center text-danger">
                            No subscribers found!
                        </td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            <nav aria-label="Page navigation example">
                <ul class="pagination float-right">
                    {{ $subscribers->links() }}
                </ul>
            </nav>
        </div>
    </div>
</x-app>